version: '3.8'
services:
  nats:
    image: nats
    container_name: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    hostname: nats
  stan:
    image: nats-streaming
    command:
      - "-ns"
      - "nats://nats:4222"
      - "-cid"
      - stan
      - "--dir"
      - datastore
      - "--store"
      - file
    container_name: stan
    links:
      - nats
    depends_on:
      - nats
    hostname: stan
